### ISSUE TITLE
ERT concepts and architecture backlog

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1022]
ERT is in the need of some thorough fundamental concepts and a description of both current and (near) future architecture.

**Backlog**
- [ ] The future fundamental data type(s) in ERT
- [ ] Data transformations
- [x] Conceptual definition of forward model, template and ensemble
- [x] The shared disk assumption
- [ ] Ensemble evaluator, algorithm pipeline and data storage
- [ ] Data communication between storage and forward models and workflows (Reporter)
- [ ] GUI interaction with ERT engine and storage (http)
- [ ] The role of Python
- [ ] Move content to docs

**What do you need?**
Feel free to add comments below about what would aid you the most going forward and I'll try to maintain an ordered backlog of things to do 🚀

**Comment by oysteoh** [comment]
GUI - should we have in the back of our minds this will move towards an HTML implementation along the plotting tools utilizing the new api on top of new storage? If How fast are we moving in that directioion? I guess the users is fine with having to gui's when running ERT and Plotting - but it would be a better experience having them both at the same place I would say.

**Comment by ManInFez** [comment]
We could use QtWebEngine to bridge the gap, and thus appear that we have one interface while we are working on the html implementation. I am guessing we not only want to have plotting, but execute ensembles, etc from the new gui?

**Comment by jondequinor** [comment]
> Data communication between storage and forward models
> The workflow Reporter

Hopefully these will become one :ring: I think the interface can remain small, and still provide ERT with enough information to know what to do, even if the contexts differ (FM on the klynga, workflow locally, home made workflow locally, etc).

>  The future fundamental data type(s) in ERT

The fundamental data types should also include data that is implicit today. E.g. the update step is probably mutating data, instead it should be a transformation that is applied in a transaction.

Designing the future ERT must prioritize moving the data complexity out of the code, and into the model.

>  The shared disk assumption

Even the _disk assumption_ needs to be stamped out of existence. State must be isolated to as few interfaces as possible (reporter, storage) so that it can be controlled.

**Comment by dafeda** [comment]
This seems tale to me.
Can we close it @sondreso ?
