### ISSUE TITLE
Replace c config reading with python

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#2536]
#### Tasks

The following tasks were proposed with strangler pattern and test driven development in mind, as with most things in life, discretion is advised.

- [x] #3847
- [x] Test and debug the construction via config dict
- [ ] Make a new parser based lark (several substeps, its own epic)
- [ ] Use a blue/green or feature flag deploy incrementally replaces the old parser

#### Blocking bugs
- [x] #2553 
- [x] #2554
- [x] #2556 
- [x] #2560
- [x] #2561 
- [x] #2567
- [x] #2571
- [x] #3801
- [x] #3802

**Comment by oysteoh** [comment]
Continued in #4823
