### ISSUE TITLE
Flaky-test initiative: Whiteboard / overview / progress

### ISSUE THREAD

**Issue by BjarneHerland** [equinor/ert#3053]
### This is a working-document tracking status of flaky tests in ERT

Newer issues tend to be added to top, hence older issues appear towards end. 

### SEGFAULT in ert_tests/gui/simulation/test_realization_view.py::test_selection_success 

- [x] #3223

Should be fixed by #3237

### GenDataConfig test
- [ ] #3151  (multiple stress-tests did not reproduce this)

Attempt to fix in #3186

### test_ensemble_evaluator_run_and_get_successful_realizations_connection_closed_no_recover 

~~This might have been introduced by https://github.com/equinor/ert/pull/3125 but probably fixed by https://github.com/equinor/ert/pull/3144~~

~~Attempt to fix in #3160~~
Probably fixed by #3246

- [x] #3137

### Issues not seen the last 2 months
If we don't get reports of new such cases, we'll just close these...

- [x] #3064 
- [x] #2824
- [x] #2434
- [x] #2435 
- [x] #2375 
- [x] #2441  (this error-message is not found in the source-code anymore)
- [x] #2669

### Port issue
- [x] #2778   _initial attempt to fix in #3063_. Fixed in https://github.com/equinor/ert/pull/3096

### Service timeout
BaseService defines default timeout=20s for several actions. These are likely to be fixed by simply increasing the timeout.

- [x] #2429  _initial attempt to fix in #3076_
- [x] #2381
- [x] #2846
- [x] #2961 

because this error most likely originates here when nothing is received from the child-process within the given timeout

https://github.com/equinor/ert/blob/9a2b7942106a6dc165be2b6c18d998bf0a045d89/ert_shared/services/_base_service.py#L187-L196
where `return None` causes
https://github.com/equinor/ert/blob/9a2b7942106a6dc165be2b6c18d998bf0a045d89/ert_shared/services/_base_service.py#L131
and finally
https://github.com/equinor/ert/blob/9a2b7942106a6dc165be2b6c18d998bf0a045d89/ert_shared/services/_base_service.py#L360-L361

However, this one comes from a different source
- [x] #2635 _(initial attempt to fix in #3078)_
because here, `_conn_info` is None. Unclear whether increasing the default timeout will fix this.

### EnkfMain lifecycle
For details see https://github.com/equinor/ert/issues/3084#issuecomment-1067856458

This group may partly be fixed by #3186

- [x] #2392
- [x] #3084  (new variant after #3021)  _initial attempt to fix in #3100_

This one is slightly different but with the same characteristics, namely two Pyhon-threads which simultaneously tries to instantiate and delete `EnkfMain`-objects
- [x] #3032 ?

### Job status timeout
_Closed because this part of the code has been removed._
- [x] #1878

### Fixtures copying testcases (perhaps rather "race-condition in dark-storage"?) 
- [ ] #3052 

These cases seems to have to variations:
1. Original case in #2824 which fails with `assert 0 == 10`. This is probably caused by an empty DataFrame, i.e. something failed miserably when creating it. See e.g. https://github.com/equinor/ert/blob/ffd51e52afb310fb275e495a26b9caae138bd9ab/ert_shared/libres_facade.py#L223
3. Case from #3064 and seen from time to time (REF??) which fails with `AssertionError: 25 != 22`. This is caused by plain wrong data which may or may not be caused by the same underlying problem as 1 above, but most likely not.

A possible theory for the latter case is that copying the testcase to tmpdir also brings along data from a previous run.

### Possible race-cond in EnsembleEvaluator/Monitor
- [x] #2844    _initial attempt to fix in #3125_

### Batch-sim is not normally used in default setup - consider skipping test(s)?
See https://github.com/equinor/ert/issues/2436#issuecomment-1065223397
- [x] #2436  _initial attempt to fix in https://github.com/equinor/ert/pull/3091_
- [x] #3043 

### Unknown - TBD
- [x] #3023

**Comment by BjarneHerland** [comment]
I'm tempted to close this one now. Most tests are closed, the others have not been observed for at least 2 months. @sondreso - what say you?

**Comment by sondreso** [comment]
> I'm tempted to close this one now. Most tests are closed, the others have not been observed for at least 2 months. @sondreso - what say you?

I agree! Closing all the issues that has not been seen since the initiative ended and closing this milestone. God job! :tada:
