### ISSUE TITLE
Experiment Server

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#3437]
This is an issue for tracking the experiment server milestone.

**Other points:** 

- We should share IDs with storage as far as this is possible

**Milestone issues**:

* Dispatcher side
- [x] https://github.com/equinor/ert/issues/3616
- [x] https://github.com/equinor/ert/issues/3704
- [x] https://github.com/equinor/ert/issues/3706
* Client side
- [x] https://github.com/equinor/ert/issues/3681
- [x] https://github.com/equinor/ert/issues/3415
- [x] https://github.com/equinor/ert/issues/3443
- [x] https://github.com/equinor/ert/issues/3703
* Server side
- [x] https://github.com/equinor/ert/issues/3720
- [x] https://github.com/equinor/ert/issues/3699
- [x] https://github.com/equinor/ert/issues/3407
- [x] https://github.com/equinor/ert/issues/3413
- [x] https://github.com/equinor/ert/issues/3152 (_closed as too broad, but contains good discussion_)
- [x] https://github.com/equinor/ert/issues/3414
- [x] https://github.com/equinor/ert/issues/3804
- [x] https://github.com/equinor/ert/issues/3948
* Backlog
- [x] https://github.com/equinor/ert/issues/3707
- [x] https://github.com/equinor/ert/issues/3456

**Comment by jondequinor** [comment]
Should we include prefect ensembles and ert3 experiments in this milestone?

**Comment by jondequinor** [comment]
(Copied over from #3152)

Revised proposal (completing sequence diagram after final job succeeds):

```mermaid

sequenceDiagram
actor User2
actor User1
User1 ->> Server: Submit Experiment
rect rgb(191, 223, 255)
User1 ->> Server: Connect
end
Server ->> Experiment: await run() task
Experiment ->> StateMachine: Stimuli (simulation start)
StateMachine ->> StateMachine: Transition to state(0,1)
Server ->> StateMachine: Retrieve full state
StateMachine ->> Server: state0
rect rgb(191, 223, 255)
Note right of User1: Websockets event
Server --) User1: state(0)
end
Experiment ->> Evaluator: Evaluate ensemble
Evaluator -->> Experiment: Stimuli (ensemble start)
Experiment ->> StateMachine: Stimuli (ensemble start)
StateMachine ->> StateMachine: Transition to state(0,2)
rect rgb(191, 223, 191)
User2 ->> Server: Connect
end
Server ->> StateMachine: Retrieve full state
Note right of Server: New connection will be given state without any transitions after last "update state" included
StateMachine ->> Server: state(0)
rect rgb(191, 223, 191)
Note right of User2: Websockets event
Server --) User2: state(0)
end
Server ->> StateMachine: Retrieve update state
StateMachine ->> StateMachine: Transition to state(2,2)
StateMachine ->> Server: state(2)-state(0)
rect rgb(191, 223, 191)
Note right of User2: Websockets event
Server --) User2: state(2)-state(0)
end
rect rgb(191, 223, 255)
Note right of User1: Websockets event
Server --) User1: state(2)-state(0)
end
Evaluator ->> Cluster: Start remote work
loop Until all realizations are complete
    rect rgb(191, 223, 255)
    note right of Server: Websockets event from the cluster
    Cluster --) Server: Job start|update|success
    end
    Server ->> StateMachine: Stimuli (job start|update|success)
    StateMachine ->> StateMachine: Transition to state(x,y)
    opt Retrieve after time t - receive all transitions in aggregated form since last retrieval
        Server ->> StateMachine: Retrieve update state
        StateMachine ->> StateMachine: Transition to state(y,y)
        StateMachine ->> Server: state(y)-state(x)
        rect rgb(191, 223, 191)
        Note right of User2: Websockets event
        Server --) User2: state(y)-state(x)
        end
        rect rgb(191, 223, 255)
        Note right of User1: Websockets event
        Server --) User1: state(y)-state(x)
        end
    end
end
rect rgb(191, 223, 255)
note right of Server: Websockets event from the cluster
Cluster --) Server: Job success (final one)
end
Server ->> StateMachine: Stimuli (job success)
opt Potential update if completing evalutation takes time
    Server ->> StateMachine: Retrieve update state
    StateMachine ->> StateMachine: Transition to state(y,y)
    StateMachine ->> Server: state(y)-state(x)
    rect rgb(191, 223, 191)
    Note right of User2: Websockets event
    Server --) User2: state(y)-state(x)
    end
    rect rgb(191, 223, 255)
    Note right of User1: Websockets event
    Server --) User1: state(y)-state(x)
    end
end
Evaluator -->> Experiment: Stimuli (ensemble success)
Experiment ->> StateMachine: Stimuli (experiment success)
Server ->> StateMachine: Retrieve update state
StateMachine ->> StateMachine: Transition to state(END,END)
StateMachine ->> Server: state(END)-state(x)
rect rgb(191, 223, 191)
Note right of User2: Websockets event
Server --) User2: state(END)-state(x)
end
rect rgb(191, 223, 255)
Note right of User1: Websockets event
Server --) User1: state(END)-state(x)
end
```

**Comment by lars-petter-hauge** [comment]
I think it makes sense to first send the structure of entities and then use the flat structure to send events/logs on a per entity level. The client will have to handle updating their state one way or another and with this approach they should be fairly free to choose their own approach.

> After some time, check if all clients are up-to-date. User1 was at log(s0)

This is the part I'm a bit curious about, and what has given the most headache when trying to implement the `statemachine`. I don't see a good and clean way of keeping this record and implementing how all classes must behave. Either the `experiment server` needs to hold all chunks of logs sent to clients, or we would need to implement a way to retrieve indexed chunks of logs from the `statemachine
` (and still the experiment server would need to keep the knowledge of which client has retrieved which index).

I don't like the alternative of implicitly flushing the logs sent in the `statemachine` though (which is the one I'm implementing now. As in, whenever the `experiment server` asks for all new logs, the statemachine would send all currently aggregated. Hence subsequent calls for updates from the statemachine would create different results, and if any issues arise during receiving/handling it is not possible to "recreate" the content of the chunk). This is easy to implement in the statemachine, but doesn't seem that robust and requires the most logic and care in the `experiment server` to handle

**Comment by lars-petter-hauge** [comment]
> > Either the `experiment server` needs to hold all chunks of logs sent to clients
> 
> Yes, I think this is probably best. There are multiple ways to truncate logs like this should size become a problem.
> 

By truncate I suppose you also mean merge? Considering that one log entry supersedes a previous log entry, a connected user would only need the last one. Thus this logic must be implemented on server side, unless one would want the clients to handle redundant messages. The `statemachine` will also contain this logic of course.

> > I think I would like the clients to receive the same logs though, and as such one client would never be ahead of another.
> 
> Yeah, wasn't communicated well, but temporary unsynchronized clients should be fine as long as they're eventually consistent.

I agree that the behaviour should be fine, but I think(...) it adds complexity.

**Comment by lars-petter-hauge** [comment]
We've looked a bit into how the current setup is made in order to better see how the next Tracker will be made. The `sequencediagram` presented here is a draft and needs updating:

```mermaid
sequenceDiagram
    participant LegacyEnsemble
    participant Monitor.SyncWSDuplexer_loop_thread1
    participant ert_ee_run_server
    participant ert_gui_simulation_thread
    MainThread->>ert_gui_simulation_thread: RunDialog.startSimulation()
    ert_gui_simulation_thread->>ert_gui_simulation_thread: asyncio.new_event_loop()
    ert_gui_simulation_thread->>ert_ee_run_server:run_ensemble_evaluator->EnsembleEvaluator.run()
    ert_gui_simulation_thread->>LegacyEnsemble:LegacyEnsemble.evalutate
    LegacyEnsemble->>LegacyEnsemble:asyncio.new_event_loop()
    ert_ee_run_server->>ert_ee_run_server:asyncio.new_event_loop()
    Note over ert_ee_run_server: Event loop is created on EnsembleEvaluator initilization and fed to threading.Thread
    ert_ee_run_server->>Monitor.SyncWSDuplexer_loop_thread1:EnsembleEvaluator.run()->ee_monitor.create()
    MainThread->>EvaluatorTracker.DrainerThread: RunDialog.startSimulation()
    EvaluatorTracker.DrainerThread->>EvaluatorTracker.DrainerThread:asyncio.new_event_loop()
    EvaluatorTracker.DrainerThread->Monitor.SyncWSDuplexer_loop_thread2:create_ee_monitor()
    Monitor.SyncWSDuplexer_loop_thread2->Monitor.SyncWSDuplexer_loop_thread2:asyncio.new_event_loop()
```
