### ISSUE TITLE
Reorganization of module structure

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#3595]
The long term idea is that all the ert code resides in `src/ert`. In general, the module structure should support rapid development by avoiding circular imports and shotgun surgery. To do so one needs to have modules that have single responsibilities, depend (import) in the direction of stable abstract modules, and supports adding new features by adding code, not changing it. That will be an ongoing issue for the lifetime of the project, but we need to start somewhere. These following first steps are suggested (Open new issue for each of the following):

- [x] #3596
- [x] `ert3` is moved to `src/ert/ert3`
- [x] `ert3_examples` is moved to `src/ert/ert3/examples`
- [x] `ert_data` is moved to `src/ert/data`
- [x] `ert_logging` is moved to `src/ert/logging`
- [x] `ert_shared` is moved to `src/ert/shared`
- [x] `job_runner` is moved to `src/ert/job_runner`.
- [x] `libres` is moved to `src/clib`
- [x] `res` is moved to `src/ert/_c_wrappers`

**Comment by sondreso** [comment]
I think this is a very good idea, and a good ordering here is probably to go from top to bottom. See also https://github.com/equinor/ert/discussions/2227

**Comment by eivindjahren** [comment]
All the things are moved, we just need to deal with the fallout.
