### ISSUE TITLE
Improve user experience with regards to config file deprecations

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4447]
Currently, the mechanism for telling the user about deprecations in their config file is through stderr, even if they have opened the gui. This could be improved by

1. Giving suggestions for migration
2. Showing the errors in the gui when gui is opened.

We can divide this behavior into three behaviors:

```
GIVEN That there is a mistake in the config file
WHEN I open the ert config with gui 
THEN I can see the error message in the gui
AND I can copy paste the errors
```

```
GIVEN That there is a deprecated keyword in the config file
WHEN I open the ert config in cli
THEN I get suggestions for how to migrate the deprecated keyword in cli 
```

```
GIVEN That there is a deprecated keyword in the config file
WHEN I open the ert config in gui
THEN I get suggestions for how to migrate the deprecated keyword in gui
AND I can copy paste the suggestions
```

The following subtasks seem reasonable:

* [x] #4464
* [x] Catch `ConfigValidationError` and write those errors to stderr in `ert.cli.main.run_cli`
* [x] Catch `ConfigValdiationError` and display those errors in gui in `ert.gui.gert_main`
* [x] #4453
* [x] #4461
* [x] Print suggestions from `DeprecatedMigrationSuggester` to stderr when running with cli.

**Comment by valentin-krasontovitsch** [comment]
just a little clarification - would you like to introduce a new error class called `ErtValidationError`, or did you mean to use the existing `ConfigValidationError`?

**Comment by valentin-krasontovitsch** [comment]
another question - at the moment, we are logging and calling `sys.exit` (which prints to stderr) on config validation errors in `src/ert/__main__.py` - this i believe will be done for any way of invoking ert. do we want to only print the errors to stderr when we are running the ert CLI? Otherwise it would be a duplication to print the errors to stderr in `ert.cli.main.run_cli`

**Comment by eivindjahren** [comment]
@valentin-krasontovitsch I ment ConfigValidationError. Fixing it.

**Comment by eivindjahren** [comment]
@valentin-krasontovitsch I think its fine either way. When running GUI, there is no need to write to cli, but its not problematic if we also write to cli.
