### ISSUE TITLE
Investigate known issues on wiki

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#4553]
Update the wiki accordingly whenever fixing issues on this list.

https://wiki.equinor.com/wiki/index.php/Debugging
- [x] #4650
- [ ] Error: ERT would not start / ERT GUI would not open
- [ ] Error: ERT fails during the initiation stage (the forward modelling stage)
- [ ] Error: Could not find RMS_TARGET.INC
- [ ] Error: RMS calculates volumes for wrong segments
- [ ] Error: RMS stops with "RMS run failed with exit status: 137"
- [x] #4651
- [ ] Error: ERT realization runs fail with no clear message in the middle of a simulation
- [ ] Error: ERT fails during post-processing
- [ ] Error: HC thickness maps not generated
- [x] #4652
- [x] Error: ERT says vector_iget_const: Invalid index
- [x] Error message: time_map_summary_update_abort: inconsistency when updating the time map
- [x] #4653
- [x] #2088 
- [ ] Error: Ert says "buffer_fread: read beyond the length of the buffer
- [x] Error: Ert says: "matrix_assert_finite: matrix:(null) is not finite."
- [ ] #4656
- [x] #4599 
- [ ] Warning: No xauth data; using fake authentication data for X11 forwarding
- [ ] Warning: Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)
- [ ] Warning: REMOTE HOST IDENTIFICATION HAS CHANGED!
- [x] #4658
- [x] #4580
- [ ] This tool has been deprecated, use 'gio open' instead. See 'gio help open' for more info.
- [x] #4659

**Comment by mortalisk** [comment]
For point `Error: ERT has started running Eclipse and keeps running "forever" for one or more realizations` there is an indication that ert might not pick up that eclipse failed. Should we investigate or should we assume that this has already been fixed?

**Comment by oysteoh** [comment]
Lets discuss in the meeting :+1:

**Comment by mortalisk** [comment]
The inconsistencies in time map error they talk about is still live: https://github.com/equinor/ert/blob/a9092929ef81bb525f044762c6e59c3a36dffb36/src/clib/lib/enkf/time_map.cpp#L195-L127 , but our plan is https://github.com/equinor/ert/issues/3549

**Comment by mortalisk** [comment]
For the buffer_fread issue, this should no longer show in the new storage.

**Comment by oyvindeide** [comment]
Will close this as we have fixed most, if not all, the issues that were related to ert.
