### ISSUE TITLE
Make FORWARD_MODEL actually do what the documentation says

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#4634]
@eivindjahren  please add to this issue sub-issues if possible and also the background and intended way of solving it when you are done discussing possible solutions.

This epic should have issues both related to solving the argument-list, resolving of keys and also validation

**Comment by eivindjahren** [comment]
The problem is more or less captured by the following example:
``
DEFINE <FROM> aberdeen
FORWARD_MODEL COPY_FILE(<FROM>=/file/a, <TO>=A)
FORWARD_MODEL COPY_FILE(<FROM>=/file/b, <TO>=B)
FORWARD_MODEL COPY_FILE(<FROM>=/file/c, <TO>=C)
```
The `COPY_FILE` has the following list of arguments `["<FROM>", "<TO>"]` The config is actually interpreted in the following way:
```
DEFINE <FROM> aberdeen
FORWARD_MODEL COPY_FILE(aberdeen=/file/a, <TO>=A)
FORWARD_MODEL COPY_FILE(aberdeen=/file/b, <TO>=B)
FORWARD_MODEL COPY_FILE(aberdeen=/file/c, <TO>=C)
```
so now our hope is that `<FROM>` gets substitute to aberdeen and then that gets substituted to /file/a. However, this doesn't happen because there are two different lists, one for the arguments inside of the parenthesis: `[("aberdeen", "/file/a"), ("<TO>", "A")]` and one for the global arguments: `[("<FROM>", "aberdeen")]` and the first list we substitute with first and then we substitute with the second list. Since there is no aberdeen in the argument list to `COPY_FILE`, only `<TO>` gets substituted by the first list, and then in the second substitution we replace `<FROM>` with `aberdeen` so in all the instances of the `COPY_FILE` you are trying to copy a file named `aberdeen`.

**Comment by eivindjahren** [comment]
One suggestion we have had is simply to turn of substitutions on the FORWARD_MODEL keyword so that the left hand side of the define works as expected. If we go with that route then the following needs to happen:

- [ ] Add the possibility of specifying that a keyword should not have substitutions in the schema_item.
- [ ] Make FORWARD_MODEL not have substitutions done on its line
- [ ] Along the way we will have a behavior change on substitutions so that private args (inside the parenthesis) take precedence over context arguments (via `DEFINE`) so that  the documentation and tests will have to change.

**Comment by oysteoh** [comment]
We should write a small summary and publish to our users about this issue as it could hit them in some ways when we release!
