### ISSUE TITLE
Config Parsing

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#4823]
Stage 1 
- [x] Evaluate and decide on a framework to use for the parsing
- [x] Parse the user configuration file
- [x] Make a parser living on the side of the old parser 
- [x] Compare the two config files and make log statements
- [x] Use lark for observation parsing

Stage 2 
- [x] Add suggestions for migrating config to new format 
- [x] Explore if it possible to create help for the config file in VScode
- [x] Cleanup after removing old parser

Definiton of done
Old parser removed from code
