### ISSUE TITLE
Implement config linter

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#5058]
Suggestion of issues to be spawned out of this epic. Please edit / remove / add more as needed. 

- [x] #5248
- [x] #5300
- [x] #5303
- [x] #5310
- [x] #5314
- [x] #5330
- [x] #5334
- [x] Produce output a problem matcher can consume to file
- [x] Produce output a problem matcher can consume to terminal
- [x] Produce output a problem matcher can consume to suggester
- [x] Look into if it possible to add config assistance in VSCode

(Specific places to add error location will be addressed by specific issues incrementally)
