### ISSUE TITLE
Refactor snapshot usage

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/ert#5866]
while working on the many realizations issue #5273, we have looked at and rewritten some parts of the code base. In the course of that work, we saw that there is a lot of need for refactoring:

- [x] remove Step concept that sits between realizations and jobs in snapshots and events and whatnot
- [ ] consider merging snapshot and partialsnapshot class (#8054)
- [ ] make gui not use any snapshot methods (it piggybacks on the snapshots metadata - it should keep its own state in its own stuff) (#8055)
- [ ] refactor how the gui models itself and consumes data from the snapshot events (it's possibly a bit clunky at the moment) (#8056)

**Comment by jonathan-eq** [comment]
Closing this as we have created separate issues for the different points.
