### ISSUE TITLE
Verify existing unit_tests with new Scheduler

### ISSUE THREAD

**Issue by berland** [equinor/ert#6810]
Expose all unit_tests that use the JobQueue by forcing it to fail in `queue.py::__init__.py` with some exception. Then add `try_queue_and_scheduler` fixture to these tests.

A tick mark means that either the directory is not using JobQueue, or that it works with both JobQueue and Scheduler (adding skip=True is allowed, will be grepped for later). Or that testing with Scheduler is not relevant (typically running poly-case instead fo a unit-test)

* [x] all
* [x] analysis
* [x] cli #6812
* [x] config
* [x] conftest.py
* [x] dark_storage #6814 
* [x] data
* [x] ensemble_evaluator #6803 
* [x] field_utils
* [x] #6936
* [x] job_queue (dedicated porting of tests)
* [x] job_runner
* [x] run_models
* [x] scenarios
* [x] scheduler
* [x] services
* [x] shared
* [x] simulator #6820 
* [x] snapshots
* [x] status #6819 #6789 
* [x] storage
* [x] summary_response
* [x] test_async_utils.py
* [x] test_enkf_main.py
* [x] test_enkf_runpath.py
* [x] test_ert_run_context.py
* [x] test_libres_facade.py
* [x] test_load_forward_model.py
* [x] test_local_config.py
* [x] test_logging.py
* [x] test_run_path_creation.py
* [x] test_runpaths.py
* [x] test_substitution_list.py
* [x] test_summary_response.py
* [x] validation

**Comment by xjules** [comment]
All relevant tests are now using both JobQueue and Scheduler.
