### ISSUE TITLE
Enable scheduler for LSF queue by default

### ISSUE THREAD

**Issue by xjules** [equinor/ert#7187]
The goal is to enable Scheduler feature by default when using LSF queue.
Blockers:
- [x] https://github.com/equinor/komodo-releases/issues/5126
- [x] #7186 
- [x] #7203
- [x] #7439
- [x] #7208
- [x] #7215
- [x] #7221 
- [x] https://github.com/equinor/ert/issues/7345
- [x] #7418
- [x] https://github.com/equinor/scout/issues/1059
- [x] https://github.com/equinor/ert/issues/7676
- [x] https://github.com/equinor/ert/issues/7691
- [x] #7695 

Nice-to-haves:
- [x] https://github.com/equinor/ert/issues/7405
- [x] https://github.com/equinor/ert/issues/7497

Definition of Done:

 - [ ] `ert ensemble_experiment poly.ert` will run scheduler by default on LSF
