### ISSUE TITLE
Improved ERT logging

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#736]
In order to actually know what is beeing used and how it is used in ERT, we need to start gather metrics, usage and errors in our software. 

- [ ] Functionality in GUI
- [ ] All errors should be logged
- [ ] Log data from config-file which is relevant. Initiate discussion up front of what we should keep
- [ ] Workflows and forward model jobs that are being used

**Comment by markusdregi** [comment]
I think we can log the entire main-config. We should be careful logging parameters and results, but the main config should not be an issue.

**Comment by oyvindeide** [comment]
Closing this as all issues are completed.
