### ISSUE TITLE
Remove JobQueue code

### ISSUE THREAD

**Issue by xjules** [equinor/ert#7885]
Blockers:

 - [x] #7187 
 - [x] #6676 
 - [ ] Remove JobQueue SLURM driver
 - [ ] Remove JobQueue LSF driver
 - [x] #7912
 - [ ] #7985 
 - [x] #8170 
 - [x] https://github.com/equinor/ert/issues/8246
 - [x] #8200 

NB! Be aware that `--disable-scheduler` will stop working once we remove the old code, which implies that even-though users have specified LSF as queue, when running it as `test_run` with `--disable-scheduler` will want to use JobQueue LOCAL driver.

**Blocked until the feature freeze in komodo August release!**
