### ISSUE TITLE
Creating ensembes/experiments with unique names is not consistent

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#7894]
In some places in the ert gui we have enforced that experiment names and ensembles must be unique, but that is not always enforced, as it is possible to make a new experiment in Experiment manager with a duplicate name. This is mostly not a problem, but will make it hard to tell the difference when plotting for example, or doing restart of es-mda.

- [x] https://github.com/equinor/ert/issues/7892
- [x] https://github.com/equinor/ert/issues/7893
- [x] https://github.com/equinor/ert/issues/7895
- [x] https://github.com/equinor/ert/issues/7913

**Comment by oyvindeide** [comment]
Completed!
