### ISSUE TITLE
Implement DESIGN_MATRIX config keyword

### ISSUE THREAD

**Issue by xjules** [equinor/ert#8688]
The main of this is to specify an excel sheet (.xlsl) file containing the sensitivity analysis parameters. 
The argument list for `DESIGN_MATRIX` should include 
 - the path (to the excel sheet file)
 - name of the sheet with the actual design parameters (design-sheet)
 - name of the sheet with the default values (default-sheet)
 
An initial work has been already done by @oyvindeide https://github.com/equinor/ert/pull/8099

This epic should include the following features too:
 - [ ] Implement support for DESIGN_MATRIX keyword
 - [ ] Internalize parameters from DESIGN_MATRIX into storage
 - [ ] https://github.com/equinor/ert/issues/8686
 - [ ] https://github.com/equinor/ert/issues/8685

**Comment by xjules** [comment]
WIP: man sketch

DESIGN MATRIX
------
.. design_matrix:

DESIGN_MATRIX is meant used to read, validate and internalize into ert storage a design matrix given in XLSX-format.
:code:DESING_MATRIX supports from 1 to 3  positional arguments:
 - XLSX file containing design and default sheet
 - the name of the design sheet (defaults to DesignSheet)
 - the name of the default sheet (defaults to DefaultSheet)
 
Ex: `DESIGN_MATRIX poly_design.xlsx DESIGN_SHEET:DesignSheet01 DEFAULT_SHEET:DefaultSheet`

The combination with GEN_KW parameters is supported; nevertheless in case of overlapping names, ert requires the full overlap of GEN_KW parameter group with the parameters located in the design parameters otherwise it will yield a validation error. In case of the full overlap the group name will be acquired from the GEN_KW, but the actual parameter values will be read from the design matrix.

**Comment by xjules** [comment]
Completed.
